id: 51229e9eb135453b8052023a34802cc6
initial_creation_type: ocr
source_metadata:
  volumes:
    1a50063ddfa2486b82040461759999bd:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: རྡོ་རྗེ་ཕག་མོའི་སྒྲུབ་ཐབས།
      total_pages: 1902
      volume_number: 26
